# This file was generated by GoReleaser. DO NOT EDIT.
class Odh < Formula
  desc "opsworks deploy helper"
  homepage "https://github.com/gotchane/odh"
  url "https://github.com/gotchane/odh/releases/download/1.0.0/odh_1.0.0_Darwin_x86_64.tar.gz"
  version "1.0.0"
  sha256 "fef638c77a6127f25c77abdc0040eae158c7781277c52e1971b7fffcd64d1583"
  
  depends_on "go"

  def install
    bin.install "odh"
  end

  test do
    system "#{bin}/odh"
  end
end
