# This file was generated by GoReleaser. DO NOT EDIT.
class Odh < Formula
  desc "opsworks deploy helper"
  homepage "https://github.com/gotchane/odh"
  url "https://github.com/gotchane/odh/releases/download/1.0.0/odh_1.0.0_Darwin_x86_64.tar.gz"
  version "1.0.0"
  sha256 "5171761244176828a1d4563a625e9d12527466b88869f66a53e7769a79ae60dd"
  
  depends_on "go"

  def install
    bin.install "odh"
  end

  test do
    system "#{bin}/odh"
  end
end
